# Generated by Django 4.2.27 on 2025-12-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidWord',
            fields=[
                ('word', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'validWord',
            },
        ),
        migrations.DeleteModel(
            name='PhoneticPattern',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
