# Generated by Django 4.2.27 on 2026-01-02 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_validword_delete_phoneticpattern_delete_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneticComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Phonetic Component',
                'verbose_name_plural': 'Phonetic Components',
                'db_table': 'phoneticComponent',
            },
        ),
        migrations.CreateModel(
            name='PhoneticPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letters', models.CharField(max_length=10)),
                ('sound', models.CharField(max_length=10)),
                ('reference', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Phonetic Pattern',
                'verbose_name_plural': 'Phonetic Patterns',
                'db_table': 'phoneticPattern',
            },
        ),
        migrations.AlterModelOptions(
            name='validword',
            options={'verbose_name': 'Valid Word', 'verbose_name_plural': 'Valid Words'},
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(max_length=50)),
                ('phonetic', models.CharField(max_length=50)),
                ('date', models.DateField(unique=True)),
                ('phonetic_patterns', models.ManyToManyField(related_name='words', through='game.PhoneticComponent', to='game.phoneticpattern')),
            ],
            options={
                'verbose_name': 'Puzzle Word',
                'verbose_name_plural': 'Puzzle Words',
                'db_table': 'word',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='phoneticpattern',
            index=models.Index(fields=['sound'], name='phoneticPat_sound_d29736_idx'),
        ),
        migrations.AddIndex(
            model_name='phoneticpattern',
            index=models.Index(fields=['letters'], name='phoneticPat_letters_216de3_idx'),
        ),
        migrations.AddField(
            model_name='phoneticcomponent',
            name='pattern',
            field=models.ForeignKey(db_column='patternId', on_delete=django.db.models.deletion.RESTRICT, to='game.phoneticpattern'),
        ),
        migrations.AddField(
            model_name='phoneticcomponent',
            name='word',
            field=models.ForeignKey(db_column='wordId', on_delete=django.db.models.deletion.CASCADE, to='game.word'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=models.Index(fields=['date'], name='word_date_ebaa63_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='phoneticcomponent',
            unique_together={('word', 'pattern')},
        ),
    ]
