# Generated by Django 4.2.27 on 2026-01-03 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('game', '0003_phoneticcomponent_phoneticpattern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('user', models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('correctGuesses', models.IntegerField(db_column='correctGuesses', default=0)),
                ('wrongGuesses', models.IntegerField(db_column='wrongGuesses', default=0)),
                ('streak', models.IntegerField(db_column='streak', default=0)),
            ],
            options={
                'verbose_name': 'User Statistics',
                'verbose_name_plural': 'User Statistics',
                'db_table': 'userStats',
            },
        ),
    ]
