# Generated by Django 4.2.27 on 2026-02-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_userstats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phoneticcomponent',
            options={'ordering': ['word', 'position'], 'verbose_name': 'Phonetic Component', 'verbose_name_plural': 'Phonetic Components'},
        ),
        migrations.AlterUniqueTogether(
            name='phoneticcomponent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='phoneticcomponent',
            name='no_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phoneticcomponent',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='phoneticcomponent',
            unique_together={('word', 'position')},
        ),
    ]
